//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Formula1_EF_CF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARRO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CARRO()
        {
            this.PILOTOCARROes = new HashSet<PILOTOCARRO>();
        }
    
        public int Id { get; set; }
        public int IdEquipe { get; set; }
        public string Modelo { get; set; }
        public int Unidade { get; set; }
        public int Ano_Fabricacao { get; set; }
    
        public virtual EQUIPE EQUIPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PILOTOCARRO> PILOTOCARROes { get; set; }

        public override string ToString()
        {
            return $"Id: {this.Id}" +
                $"\nIdEquipe: {this.IdEquipe}"+
                $"\nModelo: {this.Modelo}" +
                $"\nUnidade: {this.Unidade}" +
                $"\nAno_Fabricacao: {this.Ano_Fabricacao}";
        }
    }
}
